[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MrStegmann", email = "pjstegmann@outlook.es" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic>=2.13.5",
    "pytest>=9.1.1",
    "tinydb>=4.9.0",
    "uvicorn>=0.52.4",
]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false